name: cypress pipeline 

on:
  pull_request:   
    branches: [main]    
    types: [opened, synchronize]

jobs:
  CI:   
    name: tst app
    runs-on: ubuntu-22.04  
    steps:     
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Staging Tests ✅
        if: ${{ success() }}
        # set the merge commit status check
        # using GitHub REST API
        # see https://docs.github.com/en/rest/reference/repos#create-a-commit-status
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "Staging Tests",
            "state": "success",
            "description": "Staging tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
      # - name: Install dependencies       
      #   run: npm install    
      # - name: build project       
      #   run: npm run build      
      # - name: e2e tests
      #   uses: cypress-io/github-action@v6
      #   with:      
      #     command: npm run test:e2e
      #     start: npm run start-prod
      #     wait-on: http://localhost:5000

  