name: Fly Deploy
on:
  push:
    branches:
      - main    
jobs:
  deploy:
    if: ${{ github.event_name == 'push' && !contains(join( github.event.commits.*.message, ', '), '#skip')}} 
    name: Deploy app & tagVersion
    runs-on: ubuntu-22.04 
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}       
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.70.0        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true     
          DEFAULT_BUMP: patch
      - name: Successful deploy
        uses: rjstone/discord-webhook-notify@v1.0.4 
        if: success()
        with:
            severity: info
            details: To https://full-stack-open-pokedex-small-grass-2339.fly.dev/ by ${{ github.actor }}
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

