name: Testing stuff

on:
  pull_request:   
    branches: [main]    
    types: [opened, synchronize]

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract commit hash
        run: |
          REPO_URL=${{ github.repository }}
          COMMIT_HASH=${{ github.sha }}
          COMMIT_URL="https://github.com/${REPO_URL}/commit/${COMMIT_HASH} ,${{ github.event.pull_request.user.login }} Broke the BUild :/"
          echo "::set-output name=commit_url::$COMMIT_URL"

      - name: Failing step
        id: demo
        run: exit 1
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1.0.4 
        if: success()
        with:
            severity: info
            details: Test Succeeded!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1.0.4 
        if: failure()
        with: 
            severity: error
            details: https://github.com/${{github.repository}}/commit/${{github.sha}} , ${{ github.actor }} Broke the BUild :/
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}   