name: Testing stuff

on:
  pull_request:   
    branches: [main]    
    types: [opened, synchronize]

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract commit hash
        run: |
          COMMIT_HASH=${{ github.sha }}
          echo "Commit hash: $COMMIT_HASH"

      # - name: Failing step
      #   id: demo
      #   run: exit 1
      # - name: Test Success
      #   uses: rjstone/discord-webhook-notify@v1.0.4 
      #   if: success()
      #   with:
      #       severity: info
      #       details: Test Succeeded!
      #       webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      # - name: Test Failure
      #   uses: rjstone/discord-webhook-notify@v1.0.4 
      #   if: failure()
      #   with: 
      #       severity: error
      #       details: Test Failed!
      #       webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}   