name: Cron SChedule

on:
  schedule:
    - cron: "*/6 * * * *"   # <=== Change this value

jobs:
  simple_deployment_pipeline:    
    runs-on: ubuntu-20.04   
    steps:     
      - uses: actions/checkout@v4
      - name: test
        env:
          TEST: ${{ toJson(github)}}
        run: echo "$TEST"    